const mongoose = require("mongoose");
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../.env") });

const jobsData = [
    {
        title: "Draftsman Grade II (Cat. No. 151/2026)",
        organization: "Kerala Public Service Commission",
        department: "Kerala Ports service (Hydrographic Survey Wing)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "2 (Two)",
        qualification: "Diploma in Civil / Mechanical Engineering",
        courseRequirements: "Diploma in Civil or Mechanical Engineering from Kerala Govt. or Pass in SSLC & NTC Draftsman",
        ageMin: 18,
        ageMax: 40,
        category: "General / OBC / SC-ST",
        experience: "Fresher eligible",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Direct Recruitment, OMR / Online Exam, Verification",
        salary: "₹ 31,100 – 66,800/-",
        salaryText: "₹ 31,100 – 66,800/-",
        description: "Applications are invited online through One Time Registration from qualified candidates for appointment to Draftsman Grade II in Kerala Ports service (Hydrographic Survey Wing).",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-151-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Peon / Watchman (Cat. No. 152/2026)",
        organization: "Kerala Public Service Commission",
        department: "Kerala State Financial Enterprises (KSFE Ltd.)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "Anticipated Vacancies",
        qualification: "Pass in Standard VI (6th) or equivalent",
        courseRequirements: "Pass in Standard VI (New) or equivalent from recognized school",
        ageMin: 18,
        ageMax: 40,
        category: "General / OBC / SC-ST",
        experience: "Part-Time Employees in KSFE Ltd.",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Direct Recruitment, Written Examination, Verification",
        salary: "₹ 24,500 – 42,900/-",
        salaryText: "₹ 24,500 – 42,900/-",
        description: "Direct Recruitment from among eligible candidates for Peon/Watchman in Kerala State Financial Enterprises Ltd.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-152-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Forest Boat Driver (Cat. No. 153/2026)",
        organization: "Kerala Public Service Commission",
        department: "Forest & Wildlife Department",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "Anticipated Vacancies",
        qualification: "SSLC / 10th Standard + Boat Driver Licence",
        courseRequirements: "Pass in SSLC & possession of valid Boat Driver Certificate issued by competent authority",
        ageMin: 19,
        ageMax: 36,
        category: "General / OBC / SC-ST",
        experience: "Valid Boat Driving experience",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Practical Test (Boat Driving), OMR Exam, Medical Standard",
        salary: "₹ 26,500 – 60,700/-",
        salaryText: "₹ 26,500 – 60,700/-",
        description: "Kerala Public Service Commission invites applications for Forest Boat Driver in Forest and Wildlife department.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-153-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Forest Boat Driver (By Transfer) (Cat. No. 154/2026)",
        organization: "Kerala Public Service Commission",
        department: "Forest & Wildlife Department",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "By Transfer Vacancies",
        qualification: "SSLC / 10th Standard + Boat Driver Certificate",
        courseRequirements: "Must be an approved probationer or full member in Last Grade Service with Boat Driving Certificate",
        ageMin: 19,
        ageMax: 45,
        category: "Departmental (By Transfer)",
        experience: "Last Grade Service in Forest Dept",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Practical Test, Verification",
        salary: "₹ 26,500 – 60,700/-",
        salaryText: "₹ 26,500 – 60,700/-",
        description: "Recruitment By Transfer from qualified Last Grade employees in Forest & Wildlife Department.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-154-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Higher Secondary School Teacher - Statistics (Cat. No. 155/2026)",
        organization: "Kerala Public Service Commission",
        department: "Kerala Higher Secondary Education (SR for ST)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "Special Recruitment (ST Only)",
        qualification: "Master's Degree in Statistics + B.Ed + SET",
        courseRequirements: "Master's Degree in Statistics with minimum 50% marks, B.Ed and State Eligibility Test (SET)",
        ageMin: 20,
        ageMax: 45,
        category: "Scheduled Tribe (ST) Only",
        experience: "Fresher eligible",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Online / OMR Examination, Document Verification",
        salary: "₹ 55,200 – 1,15,300/-",
        salaryText: "₹ 55,200 – 1,15,300/-",
        description: "Special Recruitment for Scheduled Tribe candidates for Higher Secondary School Teacher (HSST Statistics).",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-155-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Draftsman Grade II / Town Planning Surveyor (Cat. No. 156/2026)",
        organization: "Kerala Public Service Commission",
        department: "Local Self Government Department (LSGD)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "Special Recruitment for SC/ST",
        qualification: "Diploma in Civil / Architectural Engineering",
        courseRequirements: "Diploma in Civil Engineering / Town Planning or NTC Certificate in Draftsman Civil",
        ageMin: 18,
        ageMax: 41,
        category: "Special Recruitment for SC/ST",
        experience: "Fresher eligible",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Written / OMR Exam, Verification",
        salary: "₹ 31,100 – 66,800/-",
        salaryText: "₹ 31,100 – 66,800/-",
        description: "Recruitment to Draftsman Grade II / Town Planning Surveyor Grade II in LSGD Planning Wing.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-156-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Higher Secondary School Teacher (Junior) Arabic (Cat. No. 157/2026)",
        organization: "Kerala Public Service Commission",
        department: "Kerala Higher Secondary Education",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "Anticipated Vacancies",
        qualification: "Master's Degree in Arabic + B.Ed + SET",
        courseRequirements: "Master's Degree in Arabic with min 50% marks, B.Ed and State Eligibility Test (SET)",
        ageMin: 20,
        ageMax: 40,
        category: "General / OBC / SC-ST",
        experience: "Fresher eligible",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "OMR Examination, Interview, Document Verification",
        salary: "₹ 45,600 – 95,600/-",
        salaryText: "₹ 45,600 – 95,600/-",
        description: "Direct Recruitment for Higher Secondary School Teacher (Junior) Arabic under Higher Secondary Education.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-157-158-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Police Constable Driver (Cat. No. 159/2026)",
        organization: "Kerala Public Service Commission",
        department: "Kerala Police Department (NCA LC/AI)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "NCA Vacancies (LC/AI)",
        qualification: "Pass in SSLC / 10th + HVD Licence + Badge",
        courseRequirements: "Pass in SSLC and valid Heavy Vehicle Driving Licence with Badge",
        ageMin: 18,
        ageMax: 39,
        category: "Latin Catholic / Anglo Indian (LC/AI)",
        experience: "Driving Experience with Heavy Vehicles",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Physical Efficiency Test, Practical Driving Test, OMR Exam",
        salary: "₹ 31,100 – 66,800/-",
        salaryText: "₹ 31,100 – 66,800/-",
        description: "NCA Recruitment for Police Constable Driver / Woman Police Constable Driver in Kerala Police.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-159-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Peon / Watchman (PT Employees) (Cat. No. 160/2026)",
        organization: "Kerala Public Service Commission",
        department: "KSFE Ltd. (IV NCA-ST)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "1 (NCA-ST)",
        qualification: "Pass in Standard VI (6th) or equivalent",
        courseRequirements: "Pass in Standard VI (New) or equivalent from recognized school",
        ageMin: 18,
        ageMax: 50,
        category: "Scheduled Tribe (ST) Only",
        experience: "Part-Time Employees in KSFE Ltd.",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Written / OMR Examination, Verification",
        salary: "₹ 24,500 – 42,900/-",
        salaryText: "₹ 24,500 – 42,900/-",
        description: "IV NCA Recruitment from among Part-Time Employees in KSFE Ltd belonging to ST category.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-160-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Peon / Watchman (PT Employees) (Cat. No. 161/2026)",
        organization: "Kerala Public Service Commission",
        department: "KSFE Ltd. (VIII NCA-ST)",
        jobType: "Kerala PSC",
        location: "Kerala (Statewide)",
        vacancies: "1 (NCA-ST)",
        qualification: "Pass in Standard VI (6th) or equivalent",
        courseRequirements: "Pass in Standard VI (New) or equivalent from recognized school",
        ageMin: 18,
        ageMax: 50,
        category: "Scheduled Tribe (ST) Only",
        experience: "Part-Time Employees in KSFE Ltd.",
        applicationStartDate: "30-09-2026",
        lastDate: "04-11-2026",
        applicationFee: "Free (Kerala PSC One Time Registration)",
        selectionProcess: "Written / OMR Examination, Verification",
        salary: "₹ 24,500 – 42,900/-",
        salaryText: "₹ 24,500 – 42,900/-",
        description: "VIII NCA Recruitment from among Part-Time Employees in KSFE Ltd belonging to ST category.",
        officialNotificationUrl: "https://www.keralapsc.gov.in/sites/default/files/2026-09/noti-161-26.pdf",
        applyUrl: "https://thulasi.psc.kerala.gov.in/thulasi/",
        isLive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

async function run() {
    const mongoUri = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/jobsense";
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB:", mongoUri);

    const collection = mongoose.connection.db.collection("jobs");
    await collection.deleteMany({});
    console.log("Cleared old jobs.");

    await collection.insertMany(jobsData);
    console.log(`Successfully populated ${jobsData.length} Kerala PSC jobs into MongoDB!`);

    const count = await collection.countDocuments();
    console.log(`Total live jobs in database: ${count}`);
    process.exit(0);
}

run().catch((err) => {
    console.error("Error populating jobs:", err);
    process.exit(1);
});
